version: '2'

services:
    mariadbcons:
        image: 'maria'
        build: ./mariadb/.
        container_name: 'mariass'
        environment: 
        - 'MYSQL_ROOT_PASSWORD=12345'
        - 'MYSQL_DATABASE=analisisf2017'
        volumes:
        - dbb:/var/lib/mysql
        ports:
        - '3306:3306'
    payaraserver: 
        image: 'payara'
        build: ./payara/.   
        container_name: 'payarass'
        depends_on:
        - 'mariadbcons'        
        ports:
        - "8181:8080"
        - "4848:4848"
        entrypoint:
        - "./wait-for-it.sh"
        - "172.17.0.2:3306"
        - "-t"
        - "60"
        - "--"
        - "bin/asadmin"
        - "start-domain"
        - "-v"
